### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mfocchi** [mfocchi/locosim#1]
- [ ] incorporate obects in world file as a separate robot that you can spawn  
- [x] clean up L8 admittance
- [ ] make uniform fixed base and floating base urdf
- [x] make basecontroller inherit from base controller fixed
- [x] use setFloaqting base joint in Pinocchio
- [x] use upload.launch to load robot_description and robot_semantic_description in ros_impedance_controller

**Comment by froscia** [comment]
- [x] from quadruped_controller: reset function (freeze base + move joints to home config)
- [x] from quadruped_controller: start up from stand up and stand down
- [ ] from quadruped_controller: save gazebo video

**Comment by froscia** [comment]
- [x]  plots: add start index and index: e.g., plotVar(time, var, start, end)

- [ ] move specific world files inside robot descriptions 
- [x] integrate ROS2 and CoppeliaSim https://www.coppeliarobotics.com/helpFiles/en/ros1Tutorial.htm

**Comment by mfocchi** [comment]
startFramework
ros_impedance_controllerfloating.launch-> ros_impedance_controller.launch



Wcontacts ->contactsW

_receivePos receivcePose

create class with fifthOrderPolynomialTrajectory and bezier

fix bug in frameJacobian that does not update with True flag need to call forawardkin and getJointJacobians

make  basecontroller dependent on basecontrollerFixed

**Comment by mfocchi** [comment]
add mujoco

add pinocchio wrapper to enable custom joint name list

add possibility to specify machine ID and launch RT critical stuff (ros impedance controller) in another machine

[ ] remove old wbc

[ ] make standup in base frame

[ ] make pronto work in sim (no updated in basepose)

**Comment by mfocchi** [comment]
Inherit base controller from fixed base controllers see these commits
https://github.com/idra-lab/robot_control/commits/wip/
